// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdENoThrsMZtgiVZEKf6UuCiFjDvZAYi0',
    appId: '1:103240003911:web:278c675781ca6c6e4f9c62',
    messagingSenderId: '103240003911',
    projectId: 'mishkat-api',
    authDomain: 'mishkat-api.firebaseapp.com',
    storageBucket: 'mishkat-api.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNCdteeuN-yMEYsiSbQ1Oroi8neC7SlQ',
    appId: '1:103240003911:android:6665a1e6ee93296f4f9c62',
    messagingSenderId: '103240003911',
    projectId: 'mishkat-api',
    storageBucket: 'mishkat-api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFNZ79Lvlu7mbBBBpdpoHwH33xkzh6ylE',
    appId: '1:103240003911:ios:d27577f2e18be20f4f9c62',
    messagingSenderId: '103240003911',
    projectId: 'mishkat-api',
    storageBucket: 'mishkat-api.firebasestorage.app',
    iosBundleId: 'com.mariyyahaziz.mishkat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFNZ79Lvlu7mbBBBpdpoHwH33xkzh6ylE',
    appId: '1:103240003911:ios:34b59eef1123569e4f9c62',
    messagingSenderId: '103240003911',
    projectId: 'mishkat-api',
    storageBucket: 'mishkat-api.firebasestorage.app',
    iosBundleId: 'com.example.mishkat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdENoThrsMZtgiVZEKf6UuCiFjDvZAYi0',
    appId: '1:103240003911:web:9708195d779d8bc24f9c62',
    messagingSenderId: '103240003911',
    projectId: 'mishkat-api',
    authDomain: 'mishkat-api.firebaseapp.com',
    storageBucket: 'mishkat-api.firebasestorage.app',
  );
}
